spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
server:
  #  address: 192.168.79.1
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.niit.share.entity
  configuration:
    map-underscore-to-camel-case: true